domain_path: /home/rd/Documents/GitHub/m-cmunext-xilinx/vitis/workspace_linux/Mobile-CMUNeXt-PlatformV7/export/Mobile-CMUNeXt-PlatformV7/sw/standalone_psu_cortexa53_0
app_src_dir: /home/rd/Xilinx/2025.1/Vitis/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
lang: c
